version: 2

builds:
  - id: linuxbuild-amd
    main: ./cmd/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  
  - id: linuxbuild-arm
    main: ./cmd/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64

  - id: macbuild
    main: ./cmd/
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  - id: winbuild
    main: ./cmd/
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [ tar.gz, binary ]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ zip, binary ]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: linuxbuild-amd-nfpms
    ids:
      - linuxbuild-amd
    package_name: "ossign"
    description: "ossign - A code signing tool"
    vendor: "OSSign"
    maintainer: OSSign <contact@ossign.org>
    file_name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - deb
      - apk
      - rpm
    bindir: /usr/local/bin

  - id: linuxbuild-arm-nfpms
    ids:
      - linuxbuild-arm
    package_name: "ossign"
    description: "ossign - A code signing tool"
    vendor: "OSSign"
    maintainer: OSSign <contact@ossign.org>
    file_name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - deb
      - apk
      - rpm
    bindir: /usr/local/bin

binary_signs:
  - id: ossign
    ids:
      - winbuild
    cmd: ossign
    signature: "${artifact}"
    args:
      - "-o"
      - ${artifact}
      - "-t"
      - "pecoff"
      - ${artifact}

release:
  github:
    owner: ossign
    name: ossign

# dockers:
#   - id: ossign-linux-amd64
#     use: docker
#     goos: linux
#     goarch: amd64
#     dockerfile: Dockerfile
#     image_templates:
#     - ghcr.io/ossign/ossign:{{ .Tag }}-linux-amd64
#     - ossign/ossign:{{ .Tag }}-linux-amd64
#   - id: ossign-linux-arm64
#     use: docker
#     goos: linux
#     goarch: arm64
#     dockerfile: Dockerfile
#     image_templates:
#     - ghcr.io/ossign/ossign:{{ .Tag }}-linux-arm64
#     - ossign/ossign:{{ .Tag }}-linux-arm64

# docker_manifests:
#   - name_template: ghcr.io/ossign/ossign:latest
#     image_templates:
#       - ghcr.io/ossign/ossign:{{ .Tag }}-linux-amd64
#       - ghcr.io/ossign/ossign:{{ .Tag }}-linux-arm64
  
#   - name_template: ghcr.io/ossign/ossign:{{ .Tag }}
#     image_templates:
#       - ghcr.io/ossign/ossign:{{ .Tag }}-linux-amd64
#       - ghcr.io/ossign/ossign:{{ .Tag }}-linux-arm64
  
#   - name_template: ossign/ossign:latest
#     image_templates:
#       - ossign/ossign:{{ .Tag }}-linux-amd64
#       - ossign/ossign:{{ .Tag }}-linux-arm64
  
#   - name_template: ossign/ossign:{{ .Tag }}
#     image_templates:
#       - ossign/ossign:{{ .Tag }}-linux-amd64
#       - ossign/ossign:{{ .Tag }}-linux-arm64

uploads:
  - name: "debpkg-amd"
    ids: ["linuxbuild-amd-nfpms"]
    method: "PUT"
    exts:
      - deb
    mode: archive
    username: "ossign-dev"
    target: https://pkg.ossign.org/debian/pool/all/main/upload
    custom_artifact_name: true
    
  
  - name: "apkpkg-amd"
    method: "PUT"
    ids: ["linuxbuild-amd-nfpms"]
    exts:
      - apk
    mode: archive
    username: "ossign-dev"
    target: https://pkg.ossign.org/alpine/all/repository
    custom_artifact_name: true
  
  - name: "rpmpkg-amd"
    method: "PUT"
    ids: ["linuxbuild-amd-nfpms"]
    exts:
      - rpm
    mode: archive
    username: "ossign-dev"
    target: https://pkg.ossign.org/rpm/upload
    custom_artifact_name: true