name: OSSign Action
description: Sign files using the ossign tool or install ossign for later use
author: OSSign

branding:
  icon: feather
  color: green

inputs:
  token:
    description: 'GitHub token with repo read access. Used to fetch the latest OSSign Binary'
    required: true
  
  installOnly:
    description: 'If true, only install ossign and config, do not sign any files'
    required: false
    default: 'false'
  
  config:
    description: 'The configuration for ossign (JSON)'
    required: false
    default: ''
  
  inputFiles:
    description: 'The files to sign (supports glob patterns)'
    required: false

  inputFile:
    description: 'The file to sign'
    required: false

  outputFile:
    description: 'The output signed file, default [inputFilename]-signed.[inputExt]'
    required: false

  fileType:
    description: 'The type of file to sign (ps, pecoff, msi, dmg, appxmanifest, jar, apk)'
    required: true
    default: 'pecoff'

outputs:
  ossignPath:
    description: 'The path to the ossign binary'
  configPath:
    description: 'The path to the config file used'
  signedFile:
    description: 'The path to the signed file (if applicable)'

runs:
  using: node24
  main: action/dist/index.js
