name: Setup OSSign
description: Sign binaries using the ossign tool
author: OSSign

branding:
  icon: feather
  color: green

inputs:
  ossign_config:
    description: 'The configuration for ossign (JSON)'
    required: true
    default: '{}' 

runs:
  using: composite
  steps:
    - name: Test
      shell: bash
      run: |
        echo "Runner OS: ${{ runner.os }}, Arch: ${{ runner.arch }}"
        echo "Runner OS2: ${{ github.runner.os }}, Arch2: ${{ github.runner.arch }}"
        echo "Runner OSe: ${{ github.os }}, Arch2: ${{ github.arch }}"
      
    - name: Install config
      if: ${{ runner.os == 'linux' }}
      shell: bash
      run: |
        echo "Runner OS: ${{ runner.os }}, Arch: ${{ github.runner.arch }}"
        mkdir /etc/ossign
        echo '${{ inputs.ossign_config }}' >> /etc/ossign/config.yaml
    
    - name: Install config
      if: ${{ runner.os == 'windows' }}
      shell: pwsh
      run: |
        Create-Item -Path "$env:ProgramData\ossign" -ItemType Directory -Force
        '${{ inputs.ossign_config }}' | Out-File -FilePath "$env:ProgramData\ossign\config.yaml" -Encoding utf8
    
    - name: Install ossign (linux/amd64,linux/arm64)
      if: ${{ runner.os == 'linux' }}
      shell: bash
      run: |
        sudo curl https://pkg.ossign.org/debian/repository.key -o /etc/apt/keyrings/gitea-ossign.asc
        echo "deb [signed-by=/etc/apt/keyrings/gitea-ossign.asc] https://pkg.ossign.org/debian all main" | sudo tee /etc/apt/sources.list.d/ossign.list
        sudo apt-get update
        sudo apt-get install -y ossign
        ossign --help
    
    - name: Install ossign
      if: ${{ runner.os == 'windows' && runner.arch != 'ARM64' }}
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/OSSign/OSSign/releases/download/latest/ossign_Windows_x86_64.exe" -OutFile "$env:ProgramFiles\ossign\ossign.exe"
        $env:Path += ";$env:ProgramFiles\ossign"
        [Environment]::SetEnvironmentVariable("Path", $env:Path, [EnvironmentVariableTarget]::Machine)
        $env:GITHUB_PATH = "$env:ProgramFiles\ossign;$env:GITHUB_PATH"
        ossign.exe --help



# URLS
# https://github.com/OSSign/OSSign/releases/download/latest/ossign_Darwin_x86_64
# https://github.com/OSSign/OSSign/releases/download/latest/ossign_Darwin_arm64
# https://github.com/OSSign/OSSign/releases/download/latest/ossign_Linux_x86_64
# https://github.com/OSSign/OSSign/releases/download/latest/ossign_Linux_arm64
# https://github.com/OSSign/OSSign/releases/download/latest/ossign_Windows_x86_64
# https://github.com/OSSign/OSSign/releases/download/latest/ossign_Windows_arm64