name: Setup OSSign
description: Sign binaries using the ossign tool
author: OSSign

branding:
  icon: feather
  color: green

inputs:
  ossign_config:
    description: 'The configuration for ossign (JSON)'
    required: true
    default: '{}' 

runs:
  using: composite
  steps:
    - name: Install config
      if: ${{ runner.os == 'linux' }}
      shell: bash
      run: |
        echo "Runner OS: ${{ runner.os }}, Arch: ${{ runner.arch }}"
        sudo mkdir /etc/ossign
        echo '${{ inputs.ossign_config }}' > /tmp/ossign-config.yml
        sudo mv /tmp/ossign-config.yml /etc/ossign/config.yaml
    
    - name: Install config
      if: ${{ runner.os == 'windows' }}
      shell: bash
      run: |
        mkdir "$ProgramFiles/ossign"
        echo '${{ inputs.ossign_config }}' > "$ProgramFiles/ossign/config.yaml"
    
    - name: Install ossign (linux/amd64,linux/arm64)
      if: ${{ runner.os == 'linux' }}
      shell: bash
      run: |
        sudo curl https://pkg.ossign.org/debian/repository.key -o /etc/apt/keyrings/gitea-ossign.asc
        echo "deb [signed-by=/etc/apt/keyrings/gitea-ossign.asc] https://pkg.ossign.org/debian all main" | sudo tee /etc/apt/sources.list.d/ossign.list
        sudo apt-get update
        sudo apt-get install -y ossign
        ossign --help
    
    - name: Install ossign
      if: ${{ runner.os == 'windows' && runner.arch != 'ARM64' }}
      shell: pwsh
      run: |
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://github.com/OSSign/OSSign/releases/latest/download/ossign_Windows_x86_64.exe" -OutFile "$env:ProgramFiles\ossign\ossign.exe"
        $env:Path += ";$env:ProgramFiles\ossign"
        [Environment]::SetEnvironmentVariable("Path", $env:Path, [EnvironmentVariableTarget]::Machine)
        $env:GITHUB_PATH = "$env:ProgramFiles\ossign;$env:GITHUB_PATH"
        ossign.exe --help



# URLS
# https://github.com/OSSign/OSSign/releases/latest/download/ossign_Darwin_x86_64
# https://github.com/OSSign/OSSign/releases/latest/download/ossign_Darwin_arm64
# https://github.com/OSSign/OSSign/releases/latest/download/ossign_Linux_x86_64
# https://github.com/OSSign/OSSign/releases/latest/download/ossign_Linux_arm64
# https://github.com/OSSign/OSSign/releases/latest/download/ossign_Windows_x86_64
# https://github.com/OSSign/OSSign/releases/latest/download/ossign_Windows_arm64