on:
  push:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: ossign/ossign/action/setup-ossign@main
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                ossign_config: |
                    {
                        "hello": "world"
                    }
            - run: ossign --help
    test-win:
        runs-on: windows-latest
        steps:
            - uses: ossign/ossign/action/setup-ossign@main
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                ossign_config: |
                    {
                        "hello": "world"
                    }
            - run: ossign --help

    test-macos:
        runs-on: macos-latest
        steps:
            - uses: ossign/ossign/action/setup-ossign@main
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                ossign_config: |
                    {
                        "hello": "world"
                    }
            - run: ossign --help
