on:
  push:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
          id-token: read
        steps:
            - uses: ossign/ossign/action/setup-ossign@main
              with:
                ossign_config: |
                    {
                        "hello": "world"
                    }
    test-win:
        runs-on: windows-latest
        permissions:
          id-token: read
        steps:
            - uses: ossign/ossign/action/setup-ossign@main
              with:
                ossign_config: |
                    {
                        "hello": "world"
                    }