on:
  workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: ossign/ossign/action/setup-ossign@main
              with:
                ossign_config: |
                    {
                        "hello": "world"
                    }
